### ISSUE TITLE
ST_DESTINATION Documentation

### ISSUE THREAD

**Issue by scoddou** [CartoDB/analytics-toolbox-core#474] opened 2024-01-23 21:50 UTC
**Describe the bug**
Is the bearing in ST_DESTINATION counter-clockwise relative east? Screen shot included with the SQL I ran. From documentation:

``
bearing: DOUBLE counter-clockwise angle from East, ranging from -180 to 180 (e.g. 0 is East, 90 is North, 180 is West, -90 is South)
``

**To Reproduce**

```sql
SELECT 
      'ORIGIN' AS TYPE
    , ST_POINT(-3.70325,40.4167) AS GEOG
UNION ALL
SELECT 
      '0 DEG' AS TYPE
    , CARTO.CARTO.ST_DESTINATION(ST_POINT(-3.70325,40.4167), 1, 0)
UNION ALL
SELECT 
      '90 DEG' AS TYPE
    , CARTO.CARTO.ST_DESTINATION(ST_POINT(-3.70325,40.4167), 1, 90)
UNION ALL
SELECT 
      '180 DEG' AS TYPE
    , CARTO.CARTO.ST_DESTINATION(ST_POINT(-3.70325,40.4167), 1, 180)
UNION ALL
SELECT 
      '-90 DEG' AS TYPE
    , CARTO.CARTO.ST_DESTINATION(ST_POINT(-3.70325,40.4167), 1, -90)
```

**Screenshots**
![image](https://github.com/CartoDB/analytics-toolbox-core/assets/97531714/36d2ae95-e866-4773-aa02-fed5c484fe74)

**Comment by vdelacruzb** [comment] 2024-01-24 09:48
Thanks for noticing. This seems like a miss match between the documentation and the real behaviour of the function. I'm adding the fix straightaway.

**Comment by scoddou** [comment] 2024-01-24 11:31
Happy to help. I need to reach out to Snowflake as well, since I was trying to use `ST_AZIMUTH` in combination with `ST_DESTINATION`. Just as a heads up, Snowflake’s documentation is also misleading for the bearing produced by `ST_AZIMUTH` ([here](https://docs.snowflake.com/en/sql-reference/functions/st_azimuth)).  It matches the image above as well, but their documentation says the angle produced should run from 0-360

Thank you for the help!

**Comment by vdelacruzb** [comment] 2024-01-25 16:01
Indeed. Again @scoddou, thanks for let us know about these kind of bugs.
I've just merged the fix so I'm proceeding to close the issue.

**Closed by vdelacruzb** 2024-01-25 16:01 UTC

**Comment by scoddou** [comment] 2024-01-26 15:14
I appreciate everything CARTO is doing to bring additional spatial functionality to cloud services, so happy to help where I can. 

@vdelacruzb I also wanted to test how ST_MAKEELLIPSE worked since it has an `angle` argument. I can submit another ticket with my testing, but not positive if it warrants updates to documentation or not (since I am not sure the intention of `angle`). Let me know if that would help as well

**Comment by vdelacruzb** [comment] 2024-02-05 16:25
ey @scoddou thanks for taking the time to use the functions an report bugs. Now that you mention `ST_MAKEELLIPSE`, I've done a quick check and it seems that the angle should be `negative clockwise` as stated in the doc but `positive clockwise` as mentioned in turf doc: https://turfjs.org/docs/#ellipse

- `angle` = 0
<img width="767" alt="Screenshot 2024-02-05 at 17 23 57" src="https://github.com/CartoDB/analytics-toolbox-core/assets/6054336/c9321ba2-e392-4dd6-b662-b8862ab19c83">

- `angle` = 10
<img width="846" alt="Screenshot 2024-02-05 at 17 23 43" src="https://github.com/CartoDB/analytics-toolbox-core/assets/6054336/c1c30d5e-483a-4998-8616-e74d90ff79ec">

If this was your question I will fix it straight away. I would say let's open tickets when you think the issue is a new topic that will need to be discussed.
